# Generated by Django 2.2.12 on 2022-01-13 11:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllPropDataKwest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sac_no', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('building_type', models.CharField(blank=True, max_length=255, null=True)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prop_blng_add', models.CharField(blank=True, max_length=255, null=True)),
                ('fda', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('metered_un', models.CharField(blank=True, max_length=255, null=True)),
                ('prop_tax_30_3_20', models.CharField(blank=True, max_length=255, null=True)),
                ('yearly_demand', models.CharField(blank=True, max_length=255, null=True)),
                ('despute', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'all_prop_data_kwest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KwestBldngSacRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('wkt', models.CharField(blank=True, max_length=254, null=True)),
                ('building_i', models.CharField(blank=True, max_length=254, null=True)),
                ('sac_number', models.CharField(blank=True, max_length=254, null=True)),
                ('mcgm_usern', models.CharField(blank=True, max_length=254, null=True)),
                ('mcgm_updat', models.CharField(blank=True, max_length=254, null=True)),
                ('sac_type', models.CharField(blank=True, max_length=254, null=True)),
                ('long', models.CharField(blank=True, max_length=254, null=True)),
                ('lat', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'KWESt_bldng_sac_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KwestBuildingUpdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sac_no', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('building_type', models.CharField(blank=True, max_length=255, null=True)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prop_blng_add', models.CharField(blank=True, max_length=255, null=True)),
                ('fda', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('metered_un', models.CharField(blank=True, max_length=255, null=True)),
                ('prop_tax_30_3_20', models.CharField(blank=True, max_length=255, null=True)),
                ('yearly_demand', models.CharField(blank=True, max_length=255, null=True)),
                ('despute', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('wing_name', models.CharField(blank=True, max_length=255, null=True)),
                ('num_flat', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('num_shops', models.CharField(blank=True, max_length=255, null=True)),
                ('num_floors', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'kwest_building_updated',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MumbaiPrabhagBoundaries3Jan2022V2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('prabhag_no', models.CharField(blank=True, max_length=254, null=True)),
                ('ward_name', models.CharField(blank=True, max_length=254, null=True)),
                ('ward_id', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'Mumbai_Prabhag_Boundaries_3Jan2022V2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MumbaiWardBoundary2Jan2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=254, null=True)),
                ('ward_id', models.CharField(blank=True, max_length=254, null=True)),
                ('ward_name_field', models.CharField(blank=True, db_column='ward_name_', max_length=254, null=True)),
            ],
            options={
                'db_table': 'mumbai_ward_boundary_2Jan2022',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ward61BuildingsOsm2Nov2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('osm_id', models.IntegerField()),
                ('building_name', models.CharField(blank=True, max_length=97, null=True)),
                ('addrstreet', models.CharField(blank=True, max_length=91, null=True)),
                ('building_type', models.CharField(blank=True, max_length=80, null=True)),
                ('roofmateri', models.CharField(blank=True, max_length=80, null=True)),
                ('osmward', models.CharField(blank=True, max_length=100, null=True)),
                ('num_flat', models.IntegerField(blank=True, default=1, null=True)),
                ('num_shops', models.IntegerField(blank=True, default=0, null=True)),
                ('num_floors', models.IntegerField(blank=True, default=1, null=True)),
                ('wing_name', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('councillor_ward', models.CharField(default='ward61', max_length=100)),
                ('admin_ward', models.CharField(default='ward-KWest', max_length=100)),
            ],
            options={
                'db_table': 'ward61_buildings_osm_2nov2021',
                'managed': False,
            },
        ),
    ]
