# Generated by Django 2.2.12 on 2022-01-15 10:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistinctGeomSacNoMumbai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('wkt', models.CharField(blank=True, max_length=255, null=True)),
                ('building_i', models.CharField(blank=True, max_length=255, null=True)),
                ('sac_number', models.CharField(blank=True, max_length=255, null=True)),
                ('mcgm_usern', models.CharField(blank=True, max_length=255, null=True)),
                ('mcgm_updat', models.CharField(blank=True, max_length=255, null=True)),
                ('sac_type', models.CharField(blank=True, max_length=255, null=True)),
                ('wing_name', models.CharField(blank=True, max_length=255, null=True)),
                ('num_flat', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('num_shops', models.CharField(blank=True, max_length=255, null=True)),
                ('num_floors', models.CharField(blank=True, max_length=255, null=True)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('building_type', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'distinct_geom_sac_no_mumbai',
                'managed': False,
            },
        ),
    ]
