# Generated by Django 2.2.12 on 2022-01-17 09:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_distinctgeomsacnomumbai'),
    ]

    operations = [
        migrations.CreateModel(
            name='MumbaiBuildingsWardPrabhagwise17Jan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('wkt', models.CharField(blank=True, max_length=255, null=True)),
                ('building_i', models.CharField(blank=True, max_length=255, null=True)),
                ('sac_number', models.CharField(blank=True, max_length=255, null=True)),
                ('mcgm_usern', models.CharField(blank=True, max_length=255, null=True)),
                ('mcgm_updat', models.CharField(blank=True, max_length=255, null=True)),
                ('sac_type', models.CharField(blank=True, max_length=255, null=True)),
                ('wing_name', models.CharField(blank=True, max_length=255, null=True)),
                ('num_flat', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('num_shops', models.CharField(blank=True, max_length=255, null=True)),
                ('num_floors', models.CharField(blank=True, max_length=255, null=True)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('building_type', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('before_geo', models.CharField(blank=True, max_length=254, null=True)),
                ('id1', models.BigIntegerField(blank=True, null=True)),
                ('prabhag_no', models.CharField(blank=True, max_length=254, null=True)),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=254, null=True)),
                ('ward_id_2', models.CharField(blank=True, max_length=254, null=True)),
                ('ward_name_field', models.CharField(blank=True, db_column='ward_name_', max_length=254, null=True)),
            ],
            options={
                'db_table': 'mumbai_buildings_ward_prabhagwise_17jan',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AllPropDataKwest',
        ),
        migrations.DeleteModel(
            name='KwestBldngSacRelation',
        ),
        migrations.DeleteModel(
            name='KwestBuildingUpdated',
        ),
        migrations.AlterModelOptions(
            name='mumbaiprabhagboundaries3jan2022v2',
            options={'managed': False, 'ordering': ['prabhag_no']},
        ),
        migrations.AlterModelOptions(
            name='mumbaiwardboundary2jan2022',
            options={'managed': False, 'ordering': ['ward_name_field']},
        ),
    ]
