# Generated by Django 4.1.3 on 2023-09-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20220117_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mumbaibuildingswardprabhagwise17jan',
            options={'managed': True},
        ),
    ]
