# Generated by Django 4.0 on 2021-12-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20211103_0757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ward61OsmBuildings',
        ),
    ]
