# Generated by Django 2.2.12 on 2021-12-23 15:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_delete_ward61osmbuildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='KwestPropertyLocationDetails',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('wkt', models.CharField(blank=True, max_length=254, null=True)),
                ('building_i', models.CharField(blank=True, max_length=254, null=True)),
                ('sac_number', models.CharField(blank=True, max_length=254, null=True)),
                ('mcgm_usern', models.CharField(blank=True, max_length=254, null=True)),
                ('mcgm_updat', models.CharField(blank=True, max_length=254, null=True)),
                ('sac_type', models.CharField(blank=True, max_length=254, null=True)),
                ('long', models.CharField(blank=True, max_length=254, null=True)),
                ('lat', models.CharField(blank=True, max_length=254, null=True)),
                ('ward', models.CharField(blank=True, max_length=254, null=True)),
                ('property_a', models.CharField(blank=True, max_length=254, null=True)),
                ('category_p', models.CharField(blank=True, max_length=254, null=True)),
                ('user_categ', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('user_cat_1', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('user_cat_2', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('user_cat_3', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('user_cat_4', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('user_cat_5', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('authority_field', models.CharField(blank=True, db_column='authority_', max_length=254, null=True)),
                ('assessee_f', models.CharField(blank=True, max_length=254, null=True)),
                ('assessee_m', models.CharField(blank=True, max_length=254, null=True)),
                ('assessee_l', models.CharField(blank=True, max_length=254, null=True)),
                ('building_n', models.CharField(blank=True, max_length=254, null=True)),
                ('building_1', models.CharField(blank=True, max_length=254, null=True)),
                ('location_n', models.CharField(blank=True, max_length=254, null=True)),
                ('landmark', models.CharField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=254, null=True)),
                ('village', models.CharField(blank=True, max_length=254, null=True)),
                ('pincode', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('billing_na', models.CharField(blank=True, max_length=254, null=True)),
                ('billing_ad', models.CharField(blank=True, max_length=254, null=True)),
                ('latitude', models.CharField(blank=True, max_length=254, null=True)),
                ('longitude', models.CharField(blank=True, max_length=254, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'kwest_property_location_details',
                'managed': False,
            },
        ),
    ]
