# Generated by Django 4.1.3 on 2023-09-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_mumbaibuildingswardprabhagwise17jan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='bwg_type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='compost_type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='device_ip',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='is_bwg',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='is_compost',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='prop_add',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='remark',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='road',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='update_time',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='updated_by',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='validity',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='building_i',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='building_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='building_type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='mcgm_updat',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='mcgm_usern',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='num_flat',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='num_floors',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='num_shops',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='region',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='sac_number',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='sac_type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='village',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='wing_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mumbaibuildingswardprabhagwise17jan',
            name='wkt',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
