# Generated by Django 2.2.12 on 2021-12-30 18:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_kwestpropertylocationdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPropDataKwest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sac_no', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('building_type', models.CharField(blank=True, max_length=255, null=True)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prop_blng_add', models.CharField(blank=True, max_length=255, null=True)),
                ('fda', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('metered_un', models.CharField(blank=True, max_length=255, null=True)),
                ('prop_tax_30_3_20', models.CharField(blank=True, max_length=255, null=True)),
                ('yearly_demand', models.CharField(blank=True, max_length=255, null=True)),
                ('despute', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'all_prop_data_kwest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KwestBldngSacRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('wkt', models.CharField(blank=True, max_length=254, null=True)),
                ('building_i', models.CharField(blank=True, max_length=254, null=True)),
                ('sac_number', models.CharField(blank=True, max_length=254, null=True)),
                ('mcgm_usern', models.CharField(blank=True, max_length=254, null=True)),
                ('mcgm_updat', models.CharField(blank=True, max_length=254, null=True)),
                ('sac_type', models.CharField(blank=True, max_length=254, null=True)),
                ('long', models.CharField(blank=True, max_length=254, null=True)),
                ('lat', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'KWESt_bldng_sac_relation',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='KwestPropertyLocationDetails',
        ),
    ]
