# Generated by Django 3.0 on 2021-11-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OsmBuildings29Oct21',
        ),
    ]
