# Generated by Django 3.0 on 2021-10-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0002_auto_20211028_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rejected_waste',
            field=models.FloatField(blank=True, db_column='rejected_waste', null=True),
        ),
    ]
