# Generated by Django 4.0 on 2021-12-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0002_delete_osmbuildings29oct21'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteSegregationDetails',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('coll_date', models.DateField(default=0.047619047619047616)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('num_wings', models.IntegerField(blank=True, null=True)),
                ('wing_name', models.CharField(blank=True, max_length=100, null=True)),
                ('building_type', models.CharField(blank=True, max_length=100, null=True)),
                ('building_bifurcation', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('num_households_premises', models.IntegerField(blank=True, null=True)),
                ('num_shops_premises', models.IntegerField(blank=True, null=True)),
                ('type_waste_generator', models.CharField(blank=True, max_length=100, null=True)),
                ('waste_segregation', models.CharField(blank=True, max_length=100, null=True)),
                ('wet_waste_before_segregation', models.IntegerField(blank=True, null=True)),
                ('dry_waste_before_segregation', models.IntegerField(blank=True, null=True)),
                ('hazardous_waste', models.IntegerField(blank=True, null=True)),
                ('compostable_waste', models.IntegerField(blank=True, null=True)),
                ('recyclable_waste', models.IntegerField(blank=True, null=True)),
                ('rejected_waste', models.IntegerField(blank=True, null=True)),
                ('composting_type', models.CharField(blank=True, max_length=100, null=True)),
                ('compost_bin_by_mcgm', models.CharField(blank=True, max_length=100, null=True)),
                ('date_notice_issued', models.DateField(blank=True, null=True)),
                ('name_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'waste_segregation_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminward', models.CharField(default='Ward-KWest', max_length=50)),
                ('councillorward', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('emp_category', models.CharField(max_length=100)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_mobile', models.IntegerField()),
            ],
            options={
                'db_table': 'employee_details',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='grievance',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='grievance',
            name='audio_src',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='grievance_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='img_src',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='grievance',
            table='grievance',
        ),
    ]
