# Generated by Django 3.1.5 on 2022-11-08 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0003_auto_20221108_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesegregationdetailsrevised2march22',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wastesegregationdetailsrevised2march22',
            name='coll_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
