# Generated by Django 3.0 on 2021-10-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0003_report_rejected_waste'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsmBuildings29Oct21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', models.TextField(blank=True, null=True)),
                ('fid', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('osm_id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('addrstreet', models.CharField(blank=True, max_length=10, null=True)),
                ('building', models.CharField(blank=True, max_length=80, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('num_flats', models.BigIntegerField(blank=True, null=True)),
                ('wings', models.BigIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'osm_buildings_29oct21',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='report',
            name='building_name',
            field=models.CharField(default='A', max_length=100),
        ),
    ]
