# Generated by Django 4.0.1 on 2022-01-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0007_auto_20220117_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('Ward', 'Ward'), ('Prabhag', 'Prabhag')], default='Ward', max_length=9),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
