# Generated by Django 2.2.12 on 2022-02-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0009_auto_20220131_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Select', 'none'), ('Citizen', 'CT'), ('Municipality Officer', 'MO'), ('Society Representative', 'SR'), ('Student Volunteer', 'SV')], default='none', max_length=9),
        ),
    ]
