# Generated by Django 2.2.12 on 2022-02-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0010_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Select', 'none'), ('CT', 'Citizen'), ('MO', 'Municipality Officer'), ('SR', 'Society Representative'), ('SV', 'Student Volunteer')], default='none', max_length=9),
        ),
    ]
