# Generated by Django 4.0.2 on 2022-03-19 08:03

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0011_auto_20220203_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingsWardWise4March',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.IntegerField()),
                ('ward_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ward_id', models.CharField(blank=True, max_length=50, null=True)),
                ('prabhag_no', models.CharField(blank=True, max_length=50, null=True)),
                ('building_name', models.CharField(blank=True, max_length=250, null=True)),
                ('road_name', models.CharField(blank=True, max_length=250, null=True)),
                ('name_jo', models.CharField(blank=True, max_length=250, null=True)),
                ('section', models.CharField(blank=True, max_length=230, null=True)),
                ('building_type', models.CharField(blank=True, max_length=30, null=True)),
                ('dry', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('wet', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('cluster_name', models.CharField(blank=True, max_length=270, null=True)),
                ('building_cluster', models.CharField(blank=True, max_length=270, null=True)),
                ('no_of_house', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'buildings_ward_wise_4march',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WasteSegregationDetailsRevised2March22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(blank=True, max_length=254, null=True)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sac_no', models.CharField(max_length=150)),
                ('building_type', models.CharField(blank=True, max_length=100, null=True)),
                ('building_cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('num_wings', models.CharField(blank=True, max_length=100, null=True)),
                ('wing_name', models.CharField(blank=True, max_length=100, null=True)),
                ('num_households_premises', models.CharField(blank=True, max_length=100, null=True)),
                ('num_shops_premises', models.CharField(blank=True, max_length=100, null=True)),
                ('approx_population', models.CharField(blank=True, max_length=100, null=True)),
                ('wet_waste', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('dry_waste', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('coll_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'waste_segregation_details_revised_2march22',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HumanResourceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(default='K/W', max_length=50)),
                ('prabhag', models.CharField(max_length=100)),
                ('road_name', models.CharField(max_length=100)),
                ('building_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('name_contact_person', models.CharField(max_length=100)),
                ('mobile_contact_person', models.CharField(default='1111111111', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)], verbose_name='Phone number')),
                ('email_contact_person', models.EmailField(max_length=50, verbose_name='Email Id')),
            ],
            options={
                'db_table': 'humanresourcedata',
                'managed': True,
            },
        ),
        
       
      
    ]
