# Generated by Django 4.0.2 on 2022-03-21 13:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20220117_0952'),
        ('zerowaste', '0011_auto_20220203_0758'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='WasteSegregationDetailsRevised2March22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(blank=True, max_length=254, null=True)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sac_no', models.CharField(blank=True, max_length=254, null=True)),
                ('building_type', models.CharField(blank=True, max_length=255, null=True)),
                ('building_cluster', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255, null=True)),
                ('cluster_name', models.CharField(blank=True, max_length=255, null=True)),
                ('num_wings', models.CharField(blank=True, max_length=255, null=True)),
                ('wing_name', models.CharField(blank=True, max_length=255, null=True)),
                ('num_households_premises', models.CharField(blank=True, max_length=255, null=True)),
                ('num_shops_premises', models.CharField(blank=True, max_length=255, null=True)),
                ('approx_population', models.CharField(blank=True, max_length=255, null=True)),
                ('wet_waste', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dry_waste', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coll_date', models.DateField(blank=True, null=True)),
                ('prabhag', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.mumbaiprabhagboundaries3jan2022v2', to_field='prabhag_no')),
                ('ward', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.mumbaiwardboundary2jan2022', to_field='ward_id')),
            ],
            options={
                'db_table': 'waste_segregation_details_revised_2march22',
                'managed': True,
            },
        ),
    ]
