# Generated by Django 4.0.2 on 2022-03-19 18:22

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0012_buildingswardwise4march_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastesegregationdetailsrevised2march22',
            options={'managed': True},
        ),
        
    ]
