# Generated by Django 4.0.2 on 2022-03-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0014_alter_wastesegregationdetailsrevised2march22_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastesegregationdetailsrevised2march22',
            options={'managed': True},
        ),
    ]
