# Generated by Django 4.0.2 on 2022-03-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0015_alter_wastesegregationdetailsrevised2march22_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastesegregationdetailsrevised2march22',
            options={'managed': False},
        ),
    ]
