# Generated by Django 4.1.3 on 2023-09-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('parent_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dry_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('wet_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('population', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'building_daily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('parent_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dry_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('wet_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('population', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'building_monthly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('parent_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dry_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('wet_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('population', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'building_yearly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrabhagDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('parent_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dry_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('wet_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('population', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'prabhag_daily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrabhagMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('parent_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dry_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('wet_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('population', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'prabhag_monthly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrabhagYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('parent_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dry_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('wet_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('population', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'prabhag_yearly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('parent_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dry_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('wet_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('population', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'region_daily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('parent_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dry_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('wet_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('population', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'region_monthly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('parent_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dry_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('wet_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('population', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'region_yearly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WardDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('parent_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dry_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('wet_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('population', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'ward_daily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WardMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('parent_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dry_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('wet_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('population', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'ward_monthly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WardYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('parent_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dry_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('wet_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_waste', models.DecimalField(decimal_places=0, max_digits=20)),
                ('population', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'ward_yearly',
                'managed': False,
            },
        ),
    ]
