# Generated by Django 4.1.7 on 2023-07-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginusers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loginusers',
            name='name',
        ),
        migrations.AlterField(
            model_name='loginusers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='loginusers',
            table='admin_login',
        ),
    ]
