# Generated by Django 4.1.7 on 2023-07-05 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0006_data_form_compost_data_username_and_more'),
        ('home', '0002_remove_loginusers_email_remove_loginusers_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_status', models.CharField(max_length=20)),
                ('task_start_date', models.DateField()),
                ('task_completion_date', models.DateField()),
                ('username', models.CharField(max_length=50)),
                ('zerowaste_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerowaste.authuser')),
            ],
        ),
    ]
